### ISSUE TITLE
Reference files multiple times

### ISSUE THREAD

**Issue by kkoehn** [openHPI/codeharbor#1249]
In ProFormA files can be referenced to multiple times.

We added support for this feature in https://github.com/openHPI/proformaxml/pull/368, but never implemented it in codeharbor.

We would have to change the relation between `TaskFile` and `fileable` to a many-to-many relation and rework some components in the UI (mainly the edit-view) to enable the user to select existing files.

**Comment by MrSerth** [comment]
Do you think that implementing this issue is absolutely necessary, or would we currently "just" duplicate a file that is referenced multiple times? In the latter case, I would see that as an enhancement rather than a bug (since importing and editing a corresponding exercise is still possible, even though a re-export is semantically different).

**Comment by kkoehn** [comment]
With the current implementation an import would fail, since the importer removes the file from the "pool" the first time it is referenced, the second time will break it.
Creating copies would indeed be an easier solution, but we would deviate from the ProFormA spec, which we tried to avoid until now if I remember correctly. If you think we can afford the deviation, I suggest using the "easy" fix as an interim solution and add an issue (with a high priority) to the backlog to refactor and fix this "the right way".

**Comment by MrSerth** [comment]
> Creating copies would indeed be an easier solution, but we would deviate from the ProFormA spec, which we tried to avoid until now if I remember correctly.

Indeed, and I am somewhat sad about that. However, allowing a file to be referenced multiple times is not just a schema change, but also a UI change we need to do. At the current stage, I am somewhat reluctant to do that, given the other topics being worked on, our priorities and the time remaining.

> If you think we can afford the deviation, I suggest using the "easy" fix as an interim solution and add an issue (with a high priority) to the backlog to refactor and fix this "the right way".

Yes, sounds good. I would agree to this solution, since it allows us to proceed with a relatively small compromise for an "edge" case that didn't appear previously. Still, we should definitely keep track of this problem with a dedicated issue and solve it "the right way" (as you suggested).
