### ISSUE TITLE
Re-enable duplication of tasks

### ISSUE THREAD

**Issue by MrSerth** [openHPI/codeharbor#902]
- [x] Add a button to the task show, allowing users to duplicate / clone the tasks.
- [x] Each file and all associated models should be copied, if suitable.  
For example, files should be duplicated as well, whereas the license should not. For labels, the relationship needs to be copied, but the labels itself not.
- [x] Update permission for the new task one: 
  - [x] The task should be private
  - [x] If the task was part of a collection or group, only re-add it to the same group / collection if the user has permission to do so (otherwise, don't add it). EDIT: This behaviour has been modified to match the comments below.

Of course, the existing task should remain untouched.

**Comment by florian-str** [comment]
> If the task was part of a collection or group, only re-add it to the same group / collection if the user has permission to do so (otherwise, don't add it).

I think that a duplicated task should not automatically be re-added to the group.

Reasons for this include:

- The task will probably (temporarily) get back into a Work-In-Progress-State, making it less useful in the group-list.
- In a group with many users, each making minor changes to better suit their specific class, will result in a cluttered group with many similar tasks.
- A teacher will in many cases only change minor details, to make the task better suited for his/ her specific class. Therefor, the additional value of the modified task is probably low.

As it is more likely, that a "private" modification is done, it seems more useful to go for an opt-in rather than opt-out solution.

**Comment by MrSerth** [comment]
> As it is more likely, that a "private" modification is done, it seems more useful to go for an opt-in rather than opt-out solution.

Alright, fine for me -- you're right, we might otherwise clutter the group with too many private copies. Let's just ensure we communicate clearly to the users what happened (and inform them that the task they duplicated is no longer part of any group / collection).

**Comment by florian-str** [comment]
As a corresponding PR (#924) was merged, this issue can be closed.
